export const jobData = [
    {
      title: 'Backend Developers',
      location: 'Makati',
      duties: [
          {
                description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
                ie:[
                  'May be assigned as a Project Leader or Sub-Leader',
                  'Does schedules for its members and workload estimation (Task level and Project level)',
                ],   
            },
                {description:'Performs basic engineering functions'},
                {description:'Ensures that activities conform to integrated management system requirements'},
                {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
            ],
      requirements: [
        'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
        'With at least 3 years experience in mobile backend development or Java based web service development (REST) using Java, JavaScript',
        'Experience in developing and creating Web services',
        'Experience in SQL and tools like Eclipse and Jenkins',
        'Nihongo certification (at least JLPT N5 level) is an advantage',
        'Working knowledge of advanced programming',
        'Excellent communications skills',
      ],
    },
    {
      title: 'C Developers',
      location: 'Makati',
      duties: [
        {
              description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
              ie:[
                'May be assigned as a Project Leader or Sub-Leader',
                'Does schedules for its members and workload estimation (Task level and Project level)',
              ],   
          },
              {description:'Performs basic engineering functions'},
              {description:'Ensures that activities conform to integrated management system requirements'},
              {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
          ],
      requirements: [
        'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
        'With at least 2 years experience using C in either actual development or unit testing (C++ experience could also be considered)',
        'PhilNITS certification is an advantage',
        'Nihongo certification (at least JLPT N5 level) is an advantage',
        'Working knowledge of advanced programming',
        'Excellent communications skills',
      ],
    },
    {
      title: 'C/C++ Developers',
      location: 'Makati, Cebu',
      duties: [
        {
              description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
              ie:[
                'May be assigned as a Project Leader or Sub-Leader',
                'Does schedules for its members and workload estimation (Task level and Project level)',
              ],   
          },
              {description:'Performs basic engineering functions'},
              {description:'Ensures that activities conform to integrated management system requirements'},
              {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
          ],
      requirements: [
        'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
        'With at least 2-year development experience using C/C++',
        'PhilNITS certification is an advantage',
        'Nihongo certification (at least JLPT N5 level) is an advantage',
        'Working knowledge of advanced programming',
        'Excellent communications skills',
      ],
    },
    {
        title: 'Data Analysts',
        location: 'Makati',
        duties: [
          {description:'Develop optimized analytical software to discover patterns, find anomalies, build models and derive insights and business values'},
          {description:'Establish scalable, efficient, automated processes for large scale data analysis, model development, model validation and scoring'},
          {description:'Work closely with software engineering teams to integrate data analysis with other software systems'},
          {description:'Participate in strategic analysis and help define roadmap for the team'},
        ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Applied Math, or related field)',
          'With at least 2 years experience in HOST system development/maintenance',
          'With at least 2 years software development experience',
          'Expertise in developing high-quality, object-oriented code (Java)',
          'Excellent communications skills',
          'Willing to learn Nihongo',
          'Open to Contractual engagement',
        ],
      },
      {
        title: 'Java Developers',
        location: 'Makati, Cebu',
        duties: [
            {
                  description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
                  ie:[
                    'May be assigned as a Project Leader or Sub-Leader',
                    'Does schedules for its members and workload estimation (Task level and Project level)',
                  ],   
              },
                  {description:'Performs basic engineering functions'},
                  {description:'Ensures that activities conform to integrated management system requirements'},
                  {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
          'With at least 2 years experience on J2EE, J2SE, or J2ME development',
          'PhilNITS certification is an advantage',
          'Nihongo certification (at least JLPT N5 level) is an advantage',
          'Working knowledge of advanced programming',
          'Excellent communications skills',
        ],
      },
      {
        title: 'Java Web Developers',
        location: 'Makati',
        duties: [
            {
                  description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
                  ie:[
                    'May be assigned as a Project Leader or Sub-Leader',
                    'Does schedules for its members and workload estimation (Task level and Project level)',
                  ],   
              },
                  {description:'Performs basic engineering functions'},
                  {description:'Ensures that activities conform to integrated management system requirements'},
                  {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
          'With at least 3 years experience in design, create and test Web application using HTML, Java (JSF, JDBC, JAX,-RS, JMX : for batch application, JUnit), use of spring or struts framework, Websphere (WAS), DB2, Jenkins',
          'Experience in developing applications for the web (Java, HTML5, PHP, JQuery) is an advantage',
          'Experience in SQL, Test creation using JUnit, and using Eclipse IDE is an advantage',
          'Nihongo certification (at least JLPT N5 level) is an advantage',
          'Working knowledge of advanced programming',
          'Excellent communications skills',
        ],
      },
      {
        title: 'Mainframe Developers',
        location: 'Eastwood',
        duties: [
          {description:'Code, unit testing, integration testing for mainframe'},
        ],
        requirements: [
          'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
          'With at least 2 years experience in HOST system development/maintenance',
          'Nihongo certification (at least JLPT N3 or N2 level)',
          'Knowledge in SQL and DB',
          'Operating system - AIX & Linux',
          'Excellent communications skills',
          'Open to Contractual engagement',
        ],
      },
      {
        title: 'Mobile Developers',
        location: 'Makati, Cebu',
        duties: [
          {description:'Work on mobile application architecture using Objective C and Java'},
          {description:'Participate in all phases of software development life cycle to convert concepts and specifications into mobile applications and features'},
          {description:'Work closely with software engineering teams to integrate data analysis with other software systems'},
          {description:'Participate in strategic analysis and help define roadmap for the team'},
        ],
        requirements: [
          'Graduate of any 4 or 5-year course related to software development (e.g. Compute Engineering, Computer Science, Electronics and Communications Engineering)',
          'With at least 2 years experience developing with iPhone and/or Android Technologies',
          'Solid experience developing with iPhone and /or Android technologies (Objective C, Cocoa, iOS SDK, and Android SDK)',
          'Expertise in developing high-quality, object-oriented code (Java)',
          'Experience detecting and correcting memory usage issues and optimizing code for application performance',
          'Excellent communications skills',
          'Open to Contractual engagement',
        ],
      },
      {
        title: 'Net Developers',
        location: 'Cebu',
        duties: [
            {
                  description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
                  ie:[
                    'May be assigned as a Project Leader or Sub-Leader',
                    'Does schedules for its members and workload estimation (Task level and Project level)',
                  ],   
              },
                  {description:'Performs basic engineering functions'},
                  {description:'Ensures that activities conform to integrated management system requirements'},
                  {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'At least 2 years development experience on C# and ASP.net',
          'Solid experience in software development experience',
          'Excellent communications skills',
          'Be adaptable, competent and an excellent team player',
        ],
      },
      {
        title: 'Network Administrators',
        location: 'Alabang, Cebu',
        duties: [
                {description:'Designing and planning the network'},
                {description:'Setting up the network'},
                {description:'Maintaining the network'},
                {description:'Expanding the network'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'Must be knowledgeable in network topology',
          'Must be familiar with Wireless Security',
          "Network certifications such as CompTIA's Network+, Cisco's CCNA, and Microsoft's MCTS: Server 2008 Network Infrastructure is an advantage",
          'Good communication skills',
          'Open to project-based engagement',
        ],
      },
      {
        title: 'PHP Developers',
        location: 'Cebu',
        duties: [
            {
                  description:  'Works under general supervision; this position is tasked with the following for its assigned project:',
                  ie:[
                    'May be assigned as a Project Leader or Sub-Leader',
                    'Does schedules for its members and workload estimation (Task level and Project level)',
                  ],   
              },
                  {description:'Performs basic engineering functions'},
                  {description:'Ensures that activities conform to integrated management system requirements'},
                  {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'At least 2 years development experience on PHP, SQL, HTML/CSS',
          'Solid experience in software development experience',
          'Excellent communications skills',
          'Be adaptable, competent and an excellent team player',
        ],
      },
      {
        title: 'Quality Assurance Engineers',
        location: 'Makati',
        duties: [
          {description:'Software Quality Assurance'},
          {description:'Create and execute test cases, validate test results'},
          {description:'Defect investigation and isolation'},
          {description:'Defect creation and report'},
        ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'Candidate should have at least 6 months to 1 year experience in SQA',
          'Familiar with SDLC (system development life cycle) and test methodologies',
          'Knowledge in shell scripting is a plus',
          'Experience in writing bug and test reports is an advantage',
          'Exposure to Linux/Unix environment is an advantage',
          'Excellent communications skills',
          'Open to Contractual engagement',
        ],
      },
      {
        title: 'Sharepoint Developers',
        location: 'Alabang',
        duties: [
            {description:  'SharePoint application development and data migration',
              }
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'With at least 3 years experience in SharePoint development',
          'Nihongo certification (at least JLPT N4 level) is an advantage',
          'Knowledge and experience in test automation tools and script creation is a plus',
          'Excellent communications skills',
        ],
      },
      {
        title: 'Software Testers',
        location: 'Alabang',
        duties: [
            {
                  description:  'Works under close supervision; this position does the following basic engineering functions for specific portion of the project such as:',
                  ie:[
                    'Test Procedure Implementation',
                    'Problem Isolation',
                    'Problem Report Creation',
                    'Test Plan Creation',
                    'Test Report Creation',
                    'May be assigned as Team Leader',
                  ],   
              },
                  {description:'Performs basic engineering functions'},
                  {description:'Ensures that activities conform to integrated management system requirements'},
                  {description:'Performs other activities which may be required as need arises provided he is qualified for these activities'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'With at least 2 years experience in testing',
          'Knowledge and experience in test automation tools and script creation is a plus',
          'ISTQB certification is a plus',
          'Six sigma certification/training is a plus',
          'PMP certification/training is a plus',
          'Excellent communications skills',
          'Willing to learn Nihongo',
        ],
      },
      {
        title: 'Technical Trainers',
        location: 'Makati',
        duties: [
             {description:  'Will be in-charge with the technical courses for the ACTION training program'},
          ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'At least 2 year-teaching/training experience in the industry or academe',
          'Has some experience in developing in C/C++ and / or Java',
          'Excellent communications skills',
          'Willing to learn Nihongo',
        ],
      },
      {
        title: 'Test Engineers',
        location: 'Alabang',
        duties: [
                  {description:'Execute basic quality assurance tasks (functional, regression test) for laptops and/or notebooks'},
                  {description:'Perform defect investigation/isolation, reporting, and bug fix verifications'},
                  {description:'Submit activity`s test and status report'},
                  {description:'Create/update test cases'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'Must be knowledgeable with laptop`s or notebook`s basic and advanced operations',
          'Must be familiar with Windows operating systems (Windows 7, 8, 8.1)',
          'Knowledge with basic test terms and principle (white-box and black-box testing, unit testing, system test) is an advantage',
          'Fresh graduates are welcome to apply',
          'Good communication skills',
          'Open to project-based engagement',
        ],
      },
      {
        title: 'Training Coordinators',
        location: 'Makati',
        duties: [
                  {description:'Coordinate AWS internal training and DTPH domain training'},
                  {description:'Train C, gen IT, and Engine subjects in AWS internal training'},
                  {description:'Submit training status report, conduct, and report problem-cause analysis'},
              ],
        requirements: [
          'Graduate of any 4 or 5-year IT-related courses (Computer Science, Engineering, or related field)',
          'Must have working experience using C/C++ language for at least 2 years',
          'Has experience in training/teaching in company or academe',
          'Has experience working in a development environment',
          'Willing to be assigned to client in Makati area',
          'Excellent communications skills, good reporting skills',
          'Nihongo certification (at least JLPT N5 level) is an advantage',
        ],
      },
  ];